### PR TITLE
Replace remaining upholstery code with server-side endpoints

### PR DESCRIPTION
**Pull request by RussellMcOrmond**
I'm using an entirely different style than with /archivalmanifest.   This creates a single server-side route for all the functions that are needed to match the client.

This is what I'm recommending with my systems hat on, but a different design can be used.  I know there are different ways of thinking for different frameworks when there is an MVC on both a client and a server.  I'd prefer if we thought of this server as existing to support the client, and part of the business logic of the client, as opposed to an established API which the client uses.  Having a server-paths which are specific to client-paths allows for easier coordination between different team members, where the work that one person is doing on the server-side doesn't bump into the other.

This current work still uses CouchDB specific type requests with CouchDB options on the client-side, but it gives a different way of looking at the separation between client and server to allow more appropriate abstractions in the future.  The idea is to have a few different things as demos so that we can decide how we want to design new functionality in the future.

### CODE REVIEW

**Comment by RussellMcOrmond** [comment]
I'm continuing along with #104 , to CouchView

I'd like some comments from @SaschaAdler as VSCode gives some help with the `await getView()` in couchview.json.js saying "await has no effect on this type of expression".  Except, it is an import of an async function, so that doesn't make sense to me.

in packaging.json.js it gives that same help for getView() but not postView(), even though both are the same types of functions as far as I can tell.

**Comment by RussellMcOrmond** [comment]
I haven't finished work on the Descriptive Metadata Uploader, but wanted to open this for review and comment ahead of that.

My hope is that this will inspire a different way of thinking of what the server-side of this application can do, rather than thinking of it as another API server.

**Comment by RussellMcOrmond** [comment]
I'll want some advise from @SaschaAdler about whether we will want to merge this prior to working on https://github.com/crkn-rcdr/Access-Platform/pull/55 or after.

**Review by SaschaAdler — COMMENTED** [review]
On the whole, this looks very good. I don't know if I'll be able to look at every bit of code in detail. A couple notes:

1. Why do you use an `action` parameter instead of using multiple JSON endpoints? Let's consider the DMD endpoints; I see one PUT endpoint for attachments, and one POST endpoint which has three "actions". We could just have three or four different endpoint routes that achieve the same thing. This also means you won't have to maintain a switch statement for actions, as the server will only run on correctly specified URLs.
2. Hardcoding database names is fine for now. Accessor will take that over for the parts of this that are Access Platform related.

**Comment by RussellMcOrmond** [comment]
I didn't want to think about possible shared libraries between different endpoints, rather than having a single .js that had everything for a given tool.  This can be refactored if that is desired, but I guess I think of extra endpoints adding complexity (at least in my brain :-) .

I'm not wedded to it and will follow what others do once a style is decided.  The main thing I wanted with this PR is to suggest we move away from thinking of the Sapindale server as being an API for a generic client, as opposed to part of the model (MVC) for specific functionality.

I believe you should review, suggest I make changes, and merge this when ready.  I want to continue work on the Descriptive Metadata Uploader, but we have some more discussions in https://github.com/crkn-rcdr/Access-Platform/pull/55 to complete to move that forward.

The main goal of this PR is to no longer be using upholstery, and to start to think about better abstracted interfaces (like `accessor`) for interacting with our data server-side.

**Comment by SaschaAdler** [comment]
Sure thing, and I agree that this server isn't going to be used by anything other than the sapindale client, and that will also be true for the access-specific admin tools that are about to be committed to the access platform repo, to which I imagine a lot of this code will be ported.

That said, this is still an HTTP API, and I see no reason why not to take advantage of that, or stick to existing definitions of HTTP method verbs. Shared resources for multiple endpoint files can live in files that start with an underscore, that will be ignored by the router, or somewhere outside of the `routes` directory altogether. I don't know what we'll settle on for that, but it shouldn't get in the way of being able to use multiple endpoints that require shared resources.

I have a few things I need to do before I take a look at the DMD code specifically, and as you said there's some groundwork to be done on that elsewhere. If you're eager to get rid of upholstery sooner than that, I'm fine with merging this as soon as you're ready.

**Pull request merged**
