### PR TITLE
Some thoughts on changes to the index

### PR DESCRIPTION
**Pull request by RussellMcOrmond**
I'm wanting feedback from @DivyaKrishnan26 and @SaschaAdler

### CODE REVIEW

**Comment by RussellMcOrmond** [comment]
"Tools we have declared "ready to be used" (production) and tools we are still working on where we want to show the progress and get feedback (technology previews)."

One possibility is to have a checkbox for "Show previews" to only show them for people we are trying to get feedback from.

**Comment by DivyaKrishnan26** [comment]
The checkbox show the progress of the technology previews? That might be something useful for getting feedback on what we are seeking.

**Comment by RussellMcOrmond** [comment]
This PR listed routes /packaging , /findduplicates and /internalmeta
We previously merged route /repository

We just merged route /archivalmanifest

I'm not sure which other routes we want to highlight in the index.

route /deposit was the demo for /archivalmanifest  , and we may decide to remove that route.

/slug is in testing?

I don't know if /manifest/id is intended to work, or what /collection is yet, but likely they don't fit in the index..

**Comment by RussellMcOrmond** [comment]
Different thoughts since the meeting.

I think Index should help with some of the training at this pont.  Having a reference to https://crkn.sharepoint.com/sites/platform/Shared%20Documents/Object%20Management%20Workflow.pdf and then a pull-down sub-list (like currently exists for "Legacy Tools" that makes a distinction between "Canadiana Platform II (current):" and "Canadiana Platform III (in development):"

That way questions like what Patty asked about whether making a change in the archivalmaifest interface meant that Beth didn't need to go into the internalmeta interface.

**Comment by SaschaAdler** [comment]
I'm merging this now. We've discussed some site hierarchy changes which I will work on in a separate PR.

**Pull request merged**
