### PR TITLE
Collection editor

### PR DESCRIPTION
**Pull request by DivyaKrishnan26**
To get a look at the collection record(unordered)

### CODE REVIEW

**Comment by SaschaAdler** [comment]
This is a very cool start. A few things I can think of off the bat:

* the slug resolver no longer works because the API calls have changed. This isn't in scope of the current PR but you'll have a hard time actually finding collections to work on. [Things look good with this one.](https://admin.canadiana.ca/collection/69429%2fs04x54f1nj9z)
* id shouldn't be editable
* the slug field should be checking the collection slug API calls to figure out if a new slug is good. of course, for this to work you need to keep track of the slug you started off with, since that's still valid
* the IIIF text editor is a bit overwrought. I think the Language and Value headers can show up above the already existing language-value pairs, and that both the existing pairs and the entry for new pairs should line up in the same element. The table isn't a bad idea but should be used for the whole component. You should also be able to clear existing values.
* ordered can be a checkbox
* public shouldn't be editable. I might change this to the date instead of a boolean
* try moving the items list to the right side of the page. I'll have more thoughts about what should actually be displayed but I imagine it can get a bit more compact
* [here's a collection with parents](https://admin.canadiana.ca/collection/69429%2fs0tb0xp6w96g). You'll need to expand the objects you get in the list.

**Comment by DivyaKrishnan26** [comment]
Perfect, I will start getting that done

**Comment by SaschaAdler** [comment]
I think you'll need to commit CollectionItems.svelte into the repo for this to work.

**Comment by DivyaKrishnan26** [comment]
Added the buttons for adding new language and enabled reset of language input field.
Svelte spinner included in as part of this(https://github.com/crkn-rcdr/sapindale/issues/75) 

- The Spinner works, tested with Archival Manifest -Slug Resolver, we could modify or add in to this spinner according to our needs.

**Pull request merged**
