### PR TITLE
Find Duplicates

### PR DESCRIPTION
**Pull request by RussellMcOrmond**
Opening PR to open discussion

### CODE REVIEW

**Comment by RussellMcOrmond** [comment]
@SaschaAdler , @DivyaKrishnan26 ,

I have a few questions.

* The older script https://github.com/crkn-rcdr/d10n/blob/master/workflow/www/demo/FD.js uses sessionStorage for remembering the values of some of the variables between reloads of the page.  Is there a better way to do this in sapindale, or should I use the same functionality?

* In https://upholstery.canadiana.ca/demo/FD.html the fieldset has a border around it which I think looks better.  I haven't quite figured out how to set that back to default, as the CSS delivered by svelte turns that border off.

* I haven't quite figured out how to align the radio buttons one under the other. The old code uses &lt;br&gt; which I know is the wrong way to do it.


I cleaned up some of the logic of the original, but kept it largely the same.

**Comment by SaschaAdler** [comment]
I've sorted out your second and third questions.

`<label>`s are inline by default; giving them `display: block` will put each on a new line.

**Comment by RussellMcOrmond** [comment]
Let me know if I should merge this, or if there are additional changes that should be made?

This is also not a "legacy tool", so we will want to decide how to organise it on the index page.

**Comment by SaschaAdler** [comment]
We might as well merge this now, and perhaps replace "legacy tools" with something else as more tools get ported.

**Pull request merged**
