### PR TITLE
First version of Drag and Drop collection items

### PR DESCRIPTION
**Pull request by DivyaKrishnan26**

### CODE REVIEW

**Comment by SaschaAdler** [comment]
As we discussed in our call, the important thing to add to this is a grabbable "handle" that triggers the drag-and-drop functionality. Clicking and dragging on the link inside the item leads to some unexpected behaviour. The handle should also change the cursor to `grab`, and when grabbed the cursor should change to `grabbing` (if it doesn't do so already; see [the cursor docs](https://developer.mozilla.org/en-US/docs/Web/CSS/cursor)).

Otherwise, this is impressive and I'm looking forward to seeing it in action.

**Comment by DivyaKrishnan26** [comment]
There is a considerable styling/alignment i am figuring out now, but the functionality is there for any feedback that i can add along the alignment fixes.

- Mainly i would want the space between the <div> to reduce and look like a series
- The icon colors can change to state any implied message, for now i have left in black.

**Review by SaschaAdler — CHANGES_REQUESTED** [review]
A few things:
* Drag and drop doesn't seem to update the labels of the items
* having the drag-and-drop pan icon get larger when performing a drag doesn't give enough input that the drag is taking place. Ideally there'd be some kind of indication around the entire item that it's being dragged. It's hard to describe this in text; I'll find an interface where this works
* The icon for what type of thing each item is looks too much like a button that can be clicked. It also isn't the correct icon yet (at least for manifests) but we can sort that out

I'll make a few small changes elsewhere in the collection editor at some point soon, and let you know when I've made the commit.

**Comment by SaschaAdler** [comment]
Here's a random UI example I've found: https://baseweb.design/components/dnd-list/

When an item is dragged, a border gets formed around the whole item, and then the whole item moves, while items not being dragged find themselves in new positions while the drag is happening.

The interface doesn't have to work exactly like this, but I think it's a good goal to move towards. Obviously unlike this interface, we're only triggering a drag with a handle, not the whole item.

**Review by SaschaAdler — APPROVED** [review]

**Pull request merged**
