### PR TITLE
Drag and drop- demo version with static list

### PR DESCRIPTION
**Pull request by DivyaKrishnan26**
Demo of drag and drop implementation in svelte

### CODE REVIEW

**Comment by SaschaAdler** [comment]
I'm confused. This doesn't use svelte-sortable-list at all, it seems. Which is fine if it doesn't work for us.

**Comment by SaschaAdler** [comment]
You don't want to be using fetch() for images; just setting the `src` attribute of an `img` tag will do the trick.

**Comment by SaschaAdler** [comment]
I'm created a very basic `testManifest` function in couch.js for returning manifest objects. This isn't what the final data will look like, exactly, but it's closer to it.

I've re-styled things a bit, also. Feel free to play with it. It might end up being more user-friendly to have the large image view on the left and the thumbnail list vertical on the right.

**Comment by SaschaAdler** [comment]
The sorting functionality works. I see console.log output when you click on a thumbnail, but I can't see it actually updating the large image (or, say, displaying its label.

There are also unnecessary disabled horizontal scroll bars under the thumbnail list, which I can't figure out how to remove.

I'd like the thumbnails to be bigger, if possible, and for their labels to be displayed along with them.

**Comment by DivyaKrishnan26** [comment]
The selection is what i am looking at now, and the css i'm yet to get the thumbnail bigger, i tried  few things yesterday but no luck. I will dig in on that today.
And will make the labels display along.

**Pull request merged**
