### PR TITLE
Collection editor component  skeleton

### PR DESCRIPTION
**Pull request by DivyaKrishnan26**
Version-1 of the collection editor
Base skeleton of the component structure, with no data being passed.

### CODE REVIEW

**Comment by SaschaAdler** [comment]
One thing that needs to happen is a refactor of the navigation pages into components.

There should be NavList and NavLink components such that index.svelte and the other pages (which need to be renamed) can have a structure like this:

```
<NavList>
  <NavLink href="/collection">Access Collections</NavLink>
  <NavLink href="/manifest">Access Manifests</NavLink>
  <NavLink href="/utilities">Utilities</NavLink>
</NavList>
```

This would significantly reduce code duplication.

**Comment by SaschaAdler** [comment]
Other things:

The Canadiana logo should be smaller, and link to the root of the site. Tools with state should be able to tell if you've made changes to the thing you're working on and warn you about leaving the page.

The "logged in" message shouldn't wrap, like this:

wrapping error

If it has to wrap (because the window is too narrow, which it wasn't in this case), it should be right-justified.

I'm not sold on the spacing of navigation links (or how close they are to the window edge) but I'd have to play around with it to find an optimal solution. Ideally once the NavLinks and NavLists are their own components we can find something universally applicable. There's also no reason why we shouldn't expect a different number than three links at a time.

**Comment by SaschaAdler** [comment]
1. "Deposit from preservation" should be deleted (for now).
2. I think we can have all of the links on one page, with a nested list for the legacy tools.

**Comment by RussellMcOrmond** [comment]
I like the nested list idea -- otherwise some staff may bookmark the ephemeral /navLink page.

**Comment by RussellMcOrmond** [comment]
I'm curious if there should be a 'home' button in the basic template...  Or maybe that isn't part of this pull...

**Comment by SaschaAdler** [comment]
There definitely needs to be a home button (or the Canadiana logo can be that, or both), but I think we need to work out a system for certain tools where the user is warned that they have unfinished work before leaving the page. (This is a common paradigm and I think there's even a standard way to do it, but I don't know what it is.)

**Comment by SaschaAdler** [comment]
I'm ready to merge this. Curious what Russell thinks.

**Pull request merged**
